import { Inter } from "next/font/google";
import "../globals.css";
import Navbar from "../components/Nav";
import Footer from "../components/Footer";
import { FaInstagram, FaTwitter, FaYoutube } from "react-icons/fa";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={[inter.className]}>
        <header className="fixed absolute z-200 top-0">
          <Navbar />
        </header>
        {children}

        <Footer />
        <footer className="bg-black p-6 dark:bg-gray-900">
          <div className="sm:flex sm:items-center sm:justify-between">
            <span className="text-sm text-white sm:text-center dark:text-gray-400">
              © 2023{" "}
              <a href="#" className="hover:underline">
                Opentrip
              </a>
              . All Rights Reserved.
            </span>
            <div className="flex mt-4 sm:justify-center sm:mt-0">
              <a
                href="#"
                className="text-white hover:text-gray-200 dark:hover:text-white"
              >
                <FaInstagram />
                <span className="sr-only">Instagram page</span>
              </a>
              <a
                href="#"
                className="text-white hover:text-gray-200 dark:hover:text-white ms-5"
              >
                <FaTwitter />
                <span className="sr-only">Twitter page</span>
              </a>
              <a
                href="#"
                className="text-white hover:text-gray-200 dark:hover:text-white ms-5"
              >
                <FaYoutube />
                <span className="sr-only">Youtube page</span>
              </a>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
